source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
target :HJweibo do
  pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
  pod "AFNetworking"
  pod 'SVProgressHUD', '~> 1.1.3'
  pod 'MJExtension', '~> 3.0.10'
  pod 'SDWebImage', '~> 3.7.4'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Bugly', '~> 2.4.8'
  pod 'MLeaksFinder'
  pod 'YYKit', '~> 1.0.9'
end
